wjweb/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogindex, name="index"), 
    path('<int:pk>', views.blogdetail, name='blog-detail'), 
    path('myposts/', views.mypostsview, name='myposts'), 
    path('mydrafts/', views.mydraftsview, name='mydrafts'), 
    path('create/', views.create_blog, name="create_blog"), 
    path('<int:pk>/update/', views.update_blog, name="update_blog"), 
]

wjweb/wjweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), 
    path('ckeditor/', include('ckeditor_uploader.urls')), 
    path('stock/', include('stock.urls')),
    path('option/', include('option.urls')),
    path('strategy/', include('strategy.urls')),
    path('crypto/', include('crypto.urls')), 
    path('realestate/', include('realestate.urls')), 
    path('blog/', include('blog.urls')),
    path('ratings/', include('ratings.urls'))
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

wjweb/blog/models.py
from django.db import models
#from tinymce.models import HTMLField
from mdeditor.fields import MDTextField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse

from datetime import datetime

# Create your models here.
#from accounts import models
#from accounts.models import CustomUser

#import importlib
#mymodels = importlib.import_module("accounts.models")
#from mymodels import CustomUser as Author
#Author = mymodels.CustomUser

#Author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE,)

#class Author(CustomUser):
    #first_name = models.CharField(max_length=200, blank=True)
    #last_name = models.CharField(max_length=200, blank=True)
    #photo = models.ImageField(upload_to="blog_author_photo/", blank=True)
    #bio = models.TextField(max_length=2000, blank=True)
    #email = models.EmailField(blank=True)

#    class Meta:
#        ordering = ['username']

#    def __str__(self):
#        return f'{self.username}'


class Tag(models.Model):
    name = models.CharField(max_length=200, blank=True)
    color = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.name

    def get_blog_count(self):
        return Blog.objects.filter(tag__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = "Tag"


class Blog(models.Model):
    #from django.apps import apps
    #Author = apps.get_model('accounts', 'CustomUser')
    #from accounts.models import CustomUser as Author
    
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=200, blank=True)
    summary = models.TextField(max_length=2000, blank=True)
    #body = MDTextField(blank=True)
    body = RichTextUploadingField(blank=True)
    #body = HTMLField(blank=True)
    pub_time = models.DateTimeField(blank=True, default=datetime.now())
    update_time = models.DateTimeField(blank=True, default=datetime.now())
    tag = models.ManyToManyField('Tag', verbose_name='Blog Tag', blank=True)
    is_draft = models.BooleanField(default=True, verbose_name='Is draft')

    def __str__(self):
        return self.title + ' - ' + self.author.username

    def get_absolute_url(self):
        return reverse('blog:blog-detail', args=[str(self.id)])

class Comment(models.Model):
    #from django.apps import apps
    #Author = apps.get_model('accounts', 'CustomUser')
    #from accounts.models import CustomUser as Author
    
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE, null=True, related_name='comments')
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, null=False)
    content = models.TextField(max_length=2000, blank=True)
    time = models.DateTimeField(blank=True)

    def __str__(self):
        return "[" + self.time.strftime("%m/%d/%Y, %H:%M:%S")+ "] " + self.author.username + "'s comment on " + self.blog.title

    class Meta:
        ordering = ['time']

wjweb/blog/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget

from .models import Blog, Comment, Tag

class BlogForm(forms.ModelForm):
    body = forms.CharField(widget = CKEditorUploadingWidget())
    class Meta:
        model = Blog
        fields = ('title', 'tag', 'body')

class DeleteNewForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = []

wjweb/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from .models import *
from .forms import BlogForm, DeleteNewForm
import markdown
from django.core.paginator import Paginator
from django.http import HttpResponse

from datetime import datetime
from django.apps import apps

usermodel = apps.get_model('accounts', 'CustomUser')

def blogindex(request):
    if request.method == 'GET':
        blog_list = Blog.objects.filter(is_draft=False).order_by('-pub_time')
        paginator = Paginator(blog_list, 7)
        page = request.GET.get('page')
        blogs = paginator.get_page(page)
        return render(request, 'blogindex.html', {'blogs': blogs})
    else:
        blog_list = Blog.objects.filter(author_id=int(request.POST['author_id']), is_draft=False).order_by('-pub_time')
        if len(blog_list) > 0:
            author_name = blog_list[0].author.username
        else:
            author_name = 'None'
        paginator = Paginator(blog_list, 7)
        page = request.POST.get('page')
        blogs = paginator.get_page(page)
        return render(request, 'bloglist_by_author.html', {'blogs': blogs, 'author_name':author_name})

        
def mypostsview(request):
    if request.method == 'POST':
        delete = get_object_or_404(Blog, id=request.POST['blog_id'])
        form = DeleteNewForm(request.POST, instance = delete)
        if form.is_valid():
            delete.delete()
            
    blog_list = Blog.objects.filter(author_id=request.user.id, is_draft=False).order_by('-pub_time')
    paginator = Paginator(blog_list, 7)
    page = request.GET.get('page')
    blogs = paginator.get_page(page)
    return render(request, 'myposts.html', {'blogs': blogs})


def mydraftsview(request):
    if request.method == 'POST':
        delete = get_object_or_404(Blog, id=request.POST['blog_id'])
        form = DeleteNewForm(request.POST, instance = delete)
        if form.is_valid():
            delete.delete()

    blog_list = Blog.objects.filter(author_id=request.user.id, is_draft=True).order_by('-update_time')
    paginator = Paginator(blog_list, 7)
    page = request.GET.get('page')
    blogs = paginator.get_page(page)
    return render(request, 'mydrafts.html', {'blogs': blogs})


def blogdetail(request, pk):
    blog = Blog.objects.get(id = int(pk))
    blog.body = markdown.markdown(
        blog.body,
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.toc',
            'markdown.extensions.codehilite',
        ]
    )
    return render(request, 'blogdetail.html', {'blog': blog, 'comments':blog.comments.all().order_by('-time'), 'ncomment':len(blog.comments.all())})


def update_blog(request, pk):
    if request.user.is_authenticated:
        user_name = request.user.get_username() 
        #blog = Blog.objects.get(id = int(pk))
        instance = get_object_or_404(Blog, id=int(pk))
        blog_author = instance.author.get_username()

        if user_name == blog_author:
            if request.method == "POST":
                form = BlogForm(request.POST, instance=instance)
                if form.is_valid():
                    blog = form.save(commit = False)
                    blog.author = request.user
                    if 'save_to_draft' in request.POST:
                        blog.update_time = datetime.now()
                        blog.is_draft = True
                    else:
                        blog.pub_time = datetime.now()
                        blog.is_draft = False
                    blog.save()
                    if blog.is_draft:
                        return redirect("blog:mydrafts")
                    else: 
                        return redirect("blog:myposts")
                else:
                    return HttpResponse('Invalid form!')
            else:
                return render(request, "update_blog.html", {"form": BlogForm(instance=instance)})
        else:
            info = "You are NOT the author of this blog!"
            return render(request, "blog_user_mismatch.html", {'info': info})
    else:
        return redirect('login')


def create_blog(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = BlogForm(request.POST)
            if form.is_valid():
                blog = form.save(commit=False)
                blog.author = request.user
                if 'save_to_draft' in request.POST:
                    blog.update_time = datetime.now()
                    blog.is_draft = True
                else:
                    blog.pub_time = datetime.now()
                    blog.is_draft = False
                
                blog.save()
                if blog.is_draft:
                    return redirect("blog:mydrafts")
                else: 
                    return redirect("blog:myposts")
            else:
                return HttpResponse('Invalid form!')
        else:
            return render(request, "create_blog.html", {"form": BlogForm()})
    else:
        return redirect('login')

wjweb/blog/templates/blog_user_mismatch.html
{% extends 'base.html' %}

{% block content %}

<center><h2>{{ info }}</h2></center>

{% endblock %}

wjweb/blog/templates/blogdetail.html
{% extends "base.html" %}

{% block blog %} class="active" {% endblock %}

{% block content %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

<style>
    img {
        max-width: 100%;
        max-height: 100%;
    }
    h1 {
        font-family: 'Verdana', sans-serif;
    }

</style> 

<div class="row" style="padding-left:25%; padding-right:25%; margin-top:15px;">
    <h1>{{ blog.title }}</h1>

    <div style='margin-top:15px;'>
    {% if blog.tag.all %}
            <p style="line-height:2;"><strong> 
            {% for tag in blog.tag.all %}
            <div style="color:#777;background-color:{{tag.color}};border-radius:5px; padding-left:4px; padding-right: 4px;margin-left:2px; margin-right:2px; display:inline-block;"> {{tag.name}} </div>
            {% endfor %}
            </strong></p>
    {% endif %}
    </div>

    <div class='col-sm-12' style='padding:0px;margin-top:5px;'>
        <div class='col-sm-6' style='padding:0px;'>
            <div style="display:inline-block;vertical-align:middle;transform:translate(0, 0);margin-right:5px;">
                <img src="{{ blog.author.head_pic.url }}" style="width:60px;height:60px;border-radius:50%;border:1px solid antiquewhite;">
            </div>

            <div style="display:inline-block;vertical-align:middle;transform:translate(0, 0);">
                <p style='margin-bottom:0px;margin-top:10%;'>{{ blog.author.username }} 
                    <button type="button" class="btn btn-default" style='padding:0px 10px;margin-left:10px;'>Follow</button>
                </p>
                <p><small style='color:#777;'>{{ blog.pub_time | date:'M d, Y' }} &#183; 5 min read &#9733;</small></p>
            </div>
        </div>
        <div class='col-sm-5' style='padding:0px;'>

        </div>
                            
    </div>

    <div class='col-sm-12' style='padding:0px;margin-top:20px;'>
        {{ blog.body | safe }} 
        <br>
    </div>

    <hr style='width:100%;'>



        {% if comments %}    
        <h4><span style="color:#f55;">{{ ncomment }}</span> comments:</h4>
            {% for comment in comments %}
            <div style="padding:10px;text-align:left;">
                <div style="display:inline-block;vertical-align:middle;transform:translate(0, -40%);">
                    <img src="{{ comment.author.head_pic.url }}" style="width:60px;height:60px;border-radius:50%;">
                </div>
                <div style="display:inline-block;margin-left:10px;">
                    <p>{{comment.author.username}} <span style="color:#888;">  <span class="glyphicon glyphicon-time"></span> <small>{{ comment.time | date:'Y-m-d H:i' }}</small></span></p>
                    <p>{{comment.content}}</p>
                </div>
            </div>
            {% endfor %}
        {% else %}
                <h4>There is no comment for this blog yet. Want to be the first commenter?</h4>
        {% endif %}


    


</div>

{% endblock %}

wjweb/blog/templates/blogindex.html
{% extends "base.html" %}

{% block blog %} class="active" {% endblock %}

{% block content %}


<div class="row" style="padding-left:10%; padding-right:10%; margin-top:15px;">
    
    <div class="col-sm-12">

    <div class="col-sm-9">

        {% for blog in blogs %}
        <div class="container-fluid" style="padding:0px;text-align:left;">            
                <div style="display:inline-block;transform:translate(0, -30%);margin-right:5px;">
                        <img src="{{ blog.author.head_pic.url }}" style="width:60px;height:60px;border-radius:50%;border:1px solid antiquewhite;">
                </div>

            <div style="display:inline-block;margin-left:10px;">
            <a href="{{ blog.get_absolute_url }}">
                <h3>{{ blog.title }}</h3>
            </a>
            <p>By: <a href="javascript:get_author_blogs({{ blog.author.id }})">{{blog.author.username}}</a>  <span class="glyphicon glyphicon-time"></span> <small>{{ blog.pub_time | date:'Y-m-d H:i' }}</small></p>
            </div>

            <div>
                <p>{{ blog.summary|linebreaks|urlize }}</p>
            </div>
        </div>
        <hr>
        {% endfor %}


        <div class="pagination">
            <span class="step-links">
                {% if blogs.has_previous %}
                    <a href="?page=1">&laquo; <button type="button" class="btn btn-primary">first</button></a>
                    <a href="?page={{ blogs.previous_page_number }}"><button type="button" class="btn btn-primary">previous</button></a>
                {% endif %}

                <span class="current">
                    Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
                </span>

                {% if blogs.has_next %}
                    <a href="?page={{ blogs.next_page_number }}"><button  type="button" class="btn btn-primary">next</button></a>
                    <a href="?page={{ blogs.paginator.num_pages }}"><button type="button" class="btn btn-primary">last</button> &raquo;</a>
                {% endif %}
            </span>
        </div>

    </div>
    
    
    <div class="col-sm-3">
        
            <h4>Recent posts:</h4>
            <ul>
                <li>    <a href="#">recent 1 blog</a></li>
                <li>    <a href="#">recent 2 blog</a></li>
                <li>    <a href="#">recent 3 blog</a></li>
            </ul>
            <h4>Most popular posts:</h4>
            <ul>
                <li>    <a href="#">top 1 blog</a></li>
                <li>    <a href="#">top 2 blog</a></li>
                <li>    <a href="#">top 3 blog</a></li>
            </ul>
            <h4>Most popular authors:</h4>
            <ul>
                <li>    <a href="#">top 1 author</a></li>
                <li>    <a href="#">top 2 author</a></li>
                <li>    <a href="#">top 3 author</a></li>
            </ul>
            <h4>Timeline</h4>
            <ul>
                <li>    <a href="#">Jan 2020</a></li>
                <li>    <a href="#">Dec 2019</a></li>
                <li>    <a href="#">Nov 2019</a></li>
                <li>    <a href="#">Oct 2019</a></li>
                <li>    <a href="#">Sep 2019</a></li>
            </ul>



        <br>

        <div class="input-group">
        <input type="text" class="form-control" placeholder="Search Blog..">
            <span class="input-group-btn">
            <button class="btn btn-default" type="button">
                <span class="glyphicon glyphicon-search"></span>
            </button>
            </span>
        </div>
        </input>
        <br>


    </div>
    </div>

</div>

<script>

    function get_author_blogs(author_id) {

        console.log(author_id);

        $.ajax({
            url: "",
            type: "post", 
            async: false, 
            data: {csrfmiddlewaretoken: "{{ csrf_token }}", 'author_id':author_id },
            //success: function(data) {
            //    location.reload();
            //}
        });
    };

</script>

{% endblock %}

wjweb/blog/templates/bloglist_by_author.html
{% extends "base.html" %}

{% block blog %} class="active" {% endblock %}

{% block content %}


<div class="row">    
    <div class="col-sm-9">

        {% if blogs %}
            <h4>Posts by {{ author_name }}<h4>
            {% for blog in blogs %}
            <div class="thumbnail" style="padding:10px;text-align:left;">
                
                <div style="display:inline-block;margin-left:10px;">
                <a href="{{ blog.get_absolute_url }}">
                    <h3>{{ blog.title }}</h3>
                </a>
                <small>{{ blog.pub_time | date:'Y-m-d H:i' }}</small>
                </div>

                <div>
                    <p>{{ blog.summary|linebreaks|urlize }}</p>
                </div>
            </div>
            {% endfor %}


            <div class="pagination">
                <span class="step-links">
                    {% if blogs.has_previous %}
                        <a href="?page=1">&laquo; <button>first</button></a>
                        <a href="?page={{ blogs.previous_page_number }}"><button>previous</button></a>
                    {% endif %}

                    <span class="current">
                        Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
                    </span>

                    {% if blogs.has_next %}
                        <a href="?page={{ blogs.next_page_number }}"><button>next</button></a>
                        <a href="?page={{ blogs.paginator.num_pages }}"><button>last</button> &raquo;</a>
                    {% endif %}
                </span>
            </div>
        {% else %}

            <h4>{{author.uername}} has NOT published any blog yet!</h4>

        {% endif %}
    </div>
    
    
    <div class="col-sm-3">
        <div class="alert alert-danger">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <h3>Ads</h3>
            <img src="https://placehold.it/50x100?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
        </div>
        <div class="alert alert-danger">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <h3>Ads</h3>
            <img src="https://placehold.it/50x100?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
        </div>
    </div>

</div>

{% endblock %}

wjweb/blog/templates/create_blog.html
{% extends 'base_accounts.html' %}

{% block content_accounts %}

<form action="{% url 'blog:create_blog' %}" method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" name="save_to_draft" value="Save as a draft" />
    <input type="submit" name="save_and_publish" value="Save and publish" />
</form>


{% endblock %}

wjweb/blog/templates/mydrafts.html
{% extends 'base_accounts.html' %}

{% block user %} class="active" {% endblock %}

{% block content_accounts %}

    <h3>My Drafts:</h3>
    
    {% if blogs %}
        <ul>
            {% for blog in blogs %}
            <li><a href="{{ blog.get_absolute_url }}"><strong>{{ blog.title }}</strong></a> (Last update at <span class="glyphicon glyphicon-time"></span> <small>{{ blog.update_time | date:'Y-m-d H:i' }}</small>) 
                <a href="{{ blog.get_absolute_url }}/update/"><button type="submit" style="margin:5px;">Edit</button></a>
                <button type="submit" style="margin:5px;" onClick="delete_blog('{{ blog.id }}')">Delete</button></li>
            {% endfor %}
        </ul>


        <div class="pagination">
            <span class="step-links">
                {% if blogs.has_previous %}
                    <a href="?page=1">&laquo; <button>first</button></a>
                    <a href="?page={{ blogs.previous_page_number }}"><button>previous</button></a>
                {% endif %}

                <span class="current">
                    Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
                </span>

                {% if blogs.has_next %}
                    <a href="?page={{ blogs.next_page_number }}"><button>next</button></a>
                    <a href="?page={{ blogs.paginator.num_pages }}"><button>last</button> &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <p>You haven't created any draft yet!</p>
    {% endif %}

<script>
    function delete_blog(blog_id) {
        if (confirm('Are you sure that your want to delete this draft?')) {
            $.ajax({
                url: "",
                type: "post",
                async: false,
                data: {csrfmiddlewaretoken: '{{ csrf_token }}', 'blog_id':blog_id },
                success: function(data) {
                    location.reload();
                }
            });
        }
    };
</script>


{% endblock %}

wjweb/blog/templates/myposts.html
{% extends 'base_accounts.html' %}

{% block user %} class="active" {% endblock %}

{% block content_accounts %}
    
    <h3>My Posts:</h3>

    {% if blogs %}
        <ul>
            {% for blog in blogs %}
            <li><a href="{{ blog.get_absolute_url }}"><strong>{{ blog.title }}</strong></a> (Published at <span class="glyphicon glyphicon-time"></span> <small>{{ blog.pub_time | date:'Y-m-d H:i' }}</small>)
            <a href="{{ blog.get_absolute_url }}/update/"><button type="submit" style="margin:5px;">Edit</button></a>
            <button type="submit" style="margin:5px;" onClick="delete_blog('{{ blog.id }}')">Delete</button></li>
            {% endfor %}
        </ul>


        <div class="pagination">
            <span class="step-links">
                {% if blogs.has_previous %}
                    <a href="?page=1">&laquo; <button>first</button></a>
                    <a href="?page={{ blogs.previous_page_number }}"><button>previous</button></a>
                {% endif %}

                <span class="current">
                    Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
                </span>

                {% if blogs.has_next %}
                    <a href="?page={{ blogs.next_page_number }}"><button>next</button></a>
                    <a href="?page={{ blogs.paginator.num_pages }}"><button>last</button> &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <p>You haven't published any blog yet!</p>
    {% endif %}


<script>
    
    function delete_blog(blog_id) {
        if (confirm('Are you sure that your want to delete this blog?')) {
            $.ajax({
                url: "",
                type: "post", 
                async: false, 
                data: {csrfmiddlewaretoken: '{{ csrf_token }}', 'blog_id':blog_id },
                success: function(data) {
                    location.reload();
                }
            });
        }
    };

</script>

{% endblock %}

wjweb/blog/templates/update_blog.html
{% extends 'base_accounts.html' %}

{% block content_accounts %}

<form  method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" name="save_to_draft" value="Save as a draft" />
    <input type="submit" name="save_and_publish" value="Save and publish" />
</form>


{% endblock %}